---
# Ceph role internal defaults
ceph_allow_fqdn_hostname: true
ceph_release: "ceph-{{ ceph_version }}-rhel-9"
cluster_spec_file: "/root/cluster-spec.yaml"
ceph_stabilization_wait_timeout: 180
ceph_health_check_retries: 10
ceph_health_check_delay: 60

# Network configuration
storage_network_vlan_id: 20
storage_mgmt_network_vlan_id: 21
external_network_vlan_id: 19
internalapi_network_vlan_id: 17
storage_network: 172.20.0.0/16
storage_mgmt_network: 172.21.0.0/16
external_network: 172.19.0.0/16
internalapi_network: 172.17.0.0/16
ip_offset: 10

# 1-based indexes into ocp inventory node.mac[]
storage_network_nic_num: 4
storage_mgmt_network_nic_num: "{{ storage_network_nic_num }}"
external_network_nic_num: 4
internalapi_network_nic_num: 3
