---
- name: Create cephx key for OpenStack client
  shell: |
    cephadm shell -- ceph auth add client.{{ ceph_client_name }} \
      mgr 'allow *' \
      mon 'profile rbd' \
      osd 'profile rbd pool=vms, profile rbd pool=volumes, profile rbd pool=backups, profile rbd pool=images'
  register: cephx_create_result
  changed_when: "'added key for' in cephx_create_result.stdout"
  failed_when: cephx_create_result.rc != 0
