---
- name: Reprovision the given nodes
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    lab: scale
    start_node: 4 #starts from zero
    number_of_nodes: 1 # -1 for till last node
    cloud: 40
    password: rdu2@xxxx
    quads_api_token: ""
    quads_hosts:
      scale: quads2.rdu2.scalelab.redhat.com
      alias: quads2.rdu3.labs.perfscale.redhat.com

  tasks:
    - name: Set QUADS host for lab
      set_fact:
        quads_host: "{{ quads_hosts[lab] }}"
      when: lab in quads_hosts

    - name: get the instackenv
      uri:
        url: "https://{{ quads_host }}/instack/cloud{{ cloud }}_ocpinventory.json"
        return_content: true
        validate_certs: false
        headers:
          Authorization: "Bearer {{ quads_api_token }}"
      register: inventory_download
      when: quads_host is defined

    - name: set fact inventory
      set_fact:
        inventory: "{{ inventory_download }}"

    - name: last index
      set_fact:
        last_node: "{{ inventory.json.nodes | length }}"
      when: number_of_nodes == -1

    - name: last_index
      set_fact:
        last_node: "{{ start_node + number_of_nodes }}"
      when: number_of_nodes != -1

    - name: get all the nodes
      set_fact:
        final_nodes: "{{ inventory.json.nodes[start_node:last_node|int] | map(attribute='pm_addr') | list }}"

    - name: print selected nodes
      debug:
        msg: "Nodes selected for reprovision: {{ final_nodes }}"

    - name: set boot order to foreman
      shell: |
        podman run --rm --dns 10.1.32.3 -it quads/badfish -H {{ item }} -u quads -p {{ password }} -i config/idrac_interfaces.yml --boot-to-type foreman
      loop: "{{ final_nodes }}"

      #- name: power cycle the node
      #shell: |
      #  podman run --rm --dns 10.1.32.3 -it quads/badfish -H {{ item }} -u quads -p {{ password }} -i config/idrac_interfaces.yml --power-cycle
      #loop: "{{ final_nodes }}"
